apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-app
  namespace: faiyaz-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      serviceAccountName: website-sa
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
