apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: faiyaz-gitops
  labels:
    name: website-service
    app: gitops
    environment: dev
spec:
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
